Adding jq and healthcheck scripts to container image.
redhat-developer/app-services-tools pull request #12
Opened 2022-03-02 13:57 UTC by DuncanDoyle

Added JQ and the healthcheck scripts to the container image. Removed "yum" from the container image, as it is no longer required.

2022-03-07 09:15 UTC, craicoverflow requested changes
Needs to be rebased.

2022-03-07 09:15 UTC, craicoverflow commented on Dockerfile
> +RUN microdnf install shadow-utils jq
Needs a rebase - I have added JQ in a previous PR: https://github.com/redhat-developer/app-services-tools/blob/main/Dockerfile#L27

2022-03-07 09:15 UTC, craicoverflow commented on Dockerfile
> +COPY scripts /home/rhoas/scripts
I've added the scripts already, though not to this location: https://github.com/redhat-developer/app-services-tools/blob/main/Dockerfile#L36

2022-05-19 12:58 UTC, wtrocki commented
Changes were backported.

2022-05-19 12:58 UTC, closed without merging